Rails.application.routes.draw do
  # Devise authentication routes (generated by Devise)
  devise_for :users

  # Resources for managing users (optional, for user profile management)
  # resources :users

  resources :films do
    resources :likes, only: [:create, :destroy] # Nested routes for likes within films
    resources :reviews, only: [:create] # Nested routes for reviews within films
  end

  # Root path (optional, customize as needed)
  root 'films#index'
end
